# Generated by Django 5.1.7 on 2025-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("image", models.ImageField(upload_to="wallpapers/")),
                ("resolution", models.CharField(max_length=20)),
            ],
        ),
    ]
