# Generated by Django 5.1.7 on 2025-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallpaper",
            name="category_media",
            field=models.CharField(
                choices=[
                    ("computer", "电脑壁纸"),
                    ("mobile", "手机壁纸"),
                    ("avatar", "头像"),
                    ("unknown", "未分类"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="wallpaper",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("computer", "电脑壁纸"),
                    ("mobile", "手机壁纸"),
                    ("avatar", "头像"),
                    ("unknown", "未分类"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
