# Generated by Django 5.1.7 on 2025-05-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0002_wallpaper_category_media_wallpaper_media_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallpaper",
            name="category_media",
        ),
    ]
