# Generated by Django 5.1.7 on 2025-05-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpapers", "0003_remove_wallpaper_category_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallpaper",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("0", "电脑壁纸"),
                    ("1", "手机壁纸"),
                    ("2", "头像"),
                    ("3", "未分类"),
                ],
                default="3",
                max_length=20,
            ),
        ),
    ]
