# Generated by Django 5.1.7 on 2025-03-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='用户邮箱')),
                ('phonenumber', models.CharField(max_length=11, null=True, verbose_name='用户手机')),
                ('login_date', models.DateTimeField(null=True, verbose_name='登录时间')),
                ('status', models.BooleanField(null=True, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('remask', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'sys_user',
            },
        ),
    ]
