# Generated by Django 5.1.7 on 2025-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="password",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
